rh-ecosystem-edge/eco-gotests

- tests/lca/imagebasedupgrade/internal/seedimage/seedimage.go
- tests/lca/imagebasedupgrade/internal/seedimage/seedimage_types.go
- tests/lca/imagebasedupgrade/mgmt/internal/mgmtconfig/config.go
- tests/lca/imagebasedupgrade/mgmt/upgrade/tests/e2e-upgrade-test.go
- tests/lca/imagebasedupgrade/mgmt/upgrade/upgrade_suite_test.go
Add proxy validation tests to upgrade test suite
> ibu mgmt: add proxy test to upgrade suite

- tests/cnf/ran/internal/cluster/cluster.go
- tests/cnf/ran/talm/internal/helper/cleanup.go
While testing the talm test suite, two robustness issues came up. One was related to the MCO daemon pod restarting mid-test, so a new error message was added to the list for retries. There was also an issue with the CGU not being deleted before the next test started, resulting in an issue similar to openshift-kni/eco-goinfra#402.
> cnf ran: fixed some talm robustness issues

- tests/lca/imagebasedupgrade/mgmt/upgrade/tests/e2e-upgrade-test.go
Remove workaround when extra manifests resource must exist before starting upgrade
> ibu mgmt: remove workaround for lca backup/restore bug

- .github/workflows/docker-image-ci.yml
- .github/workflows/docker-image-manual.yml
- .github/workflows/eco-goinfra-bump.yml
- .github/workflows/makefile.yml
`checkout` is out of date and should be updated to v4.
https://github.com/actions/checkout
> ci: update checkout to v4

- .github/workflows/eco-goinfra-bump.yml
- .github/workflows/makefile.yml
- Dockerfile
Related to: 
- https://github.com/test-network-function/cnf-certification-test/pull/2134
- https://github.com/openshift-kni/eco-goinfra/pull/459
https://groups.google.com/g/golang-announce/c/XbxouI9gY7k
> Update Go to v1.22.4

- tests/lca/imagebasedupgrade/cnf/internal/cnfclusterinfo/cnfclusterinfo.go
- tests/lca/imagebasedupgrade/cnf/internal/cnfconfig/config.go
- tests/lca/imagebasedupgrade/cnf/internal/cnfconfig/default.yaml
- tests/lca/imagebasedupgrade/cnf/internal/cnfparams/cnfvars.go
- tests/lca/imagebasedupgrade/cnf/internal/validations/post_ibu_validations.go
Additional validations to run post ibu for cnf scenarios:
- validate upgraded cluster hostname is not the same as seed
- validate upgraded cluster network configuration
- validate no seed hostname references in pod logs
- validate no seed hostname references in etcd
- validate pre-upgrade DU configs are present after upgrade
- validate test workload pods are running without errors
- validate pre-upgrade files written to PVs are preserved during upgrade
- validate no images are being pulled after upgrade
- validate no seed references in the exported metrics
- validate no seed references in the exported logs
> ibu cnf: post upgrade validations

- tests/cnf/ran/talm/internal/tsparams/consts.go
- tests/cnf/ran/talm/internal/tsparams/talmvars.go
- tests/cnf/ran/talm/tests/talm_precache.go
To support different image names as they change across versions, the excluded image is now pulled from the Prometheus pod on the cluster. It also only deletes the excluded image if it is found to avoid deleting all spoke images when it is not found.
cc: @yliu127 @josclark42
> cnf ran: talm precache excluded image fix

- tests/hw-accel/kmm/mcm/tests/webhook-test.go
CRD changed the way field `spokeNamespace` is acting. Updating test
> hw-accel: fix KMM test

- tests/assisted/ztp/operator/tests/https-webserver-setup-test.go
- tests/assisted/ztp/operator/tests/image-service-statefulset.go
- tests/assisted/ztp/operator/tests/infraenv-multiarch-image.go
- tests/assisted/ztp/operator/tests/unauthenticated-registries.go
Add disruptive label to prevent flaky failures in operator suite
> assisted ztp: add disruptive label to operator tests

- tests/lca/imagebasedupgrade/mgmt/negative/internal/tsparams/const.go
- tests/lca/imagebasedupgrade/mgmt/negative/tests/ibu-invalid-next-stage.go
> lca: add negative test for patching the stage from idle to rollback.

- tests/lca/imagebasedupgrade/cnf/upgrade-talm/internal/tsparams/const.go
- tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/e2e-upgrade-test.go
@mcornea , @klaskosk , Please review this PR when you have a moment. Thanks!
adding 'rollback after a successful upgrade' test steps within e2e-upgrade-test.go file which serves below purposes.
1. covering test case - rollback after a successful upgrade, 
2. removing dependency other test functional test cases exists within "upgrade-talm" test suite.
**High-level test automation code change summary:-**
updating e2e-upgrade-test.go file to include below steps in AfterAll()
func1
create rollback cgu and wait until the cgu report completed. 
func2
create finalize cgu and wait until the cgu report completed. 
func3
delete rollback cgu
func4
delete finalize cgu
> ibu cnf: add 'rollback after a successful upgrade' test

- tests/lca/imagebasedupgrade/cnf/internal/cnfclusterinfo/cnfclusterinfo.go
- tests/lca/imagebasedupgrade/cnf/internal/validations/post_ibu_validations.go
- exclude operators whose version does not change during upgrade
- exclude default sriov nnp which is not present in 4.16
- exclude null characters when validating seed entries in etcd for a cleaner output
> lca: cnf exclude operators and sriov nnp from post validation checks

- tests/lca/imagebasedupgrade/internal/safeapirequest/safeapirequest.go
- tests/lca/imagebasedupgrade/mgmt/negative/internal/tsparams/const.go
- tests/lca/imagebasedupgrade/mgmt/negative/negative_suite_test.go
- tests/lca/imagebasedupgrade/mgmt/negative/tests/ibu-invalid-next-stage.go
- tests/lca/imagebasedupgrade/mgmt/negative/tests/immutable-seedimage.go
- tests/lca/imagebasedupgrade/mgmt/negative/tests/missing-backup-location.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/oadp/const.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/oadp/dataprotectionapplication.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/oadp/dataprotectionapplicationlist.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/velero/backup.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/velero/backupstoragelocation.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/velero/backupstoragelocationlist.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/velero/restore.go
- vendor/modules.txt
Add missing DPA test to the negative test suite. Also update IBU clean up to be contained in one suite level AfterEach container.
> ibu mgmt: add missing dpa test

- tests/lca/imagebasedupgrade/cnf/upgrade-talm/internal/tsparams/const.go
- tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/rollback-after-failed-upgrade-test.go
adding test case 'rollback after a failed upgrade'
> ready-for-final-review: ibu cnf: add 'rollback after a failed upgrade' test

- tests/lca/imagebasedupgrade/mgmt/upgrade/tests/e2e-upgrade-test.go
This will help ensuring an additional test is ran.
> ibu mgmt: move the set to idle to after all.

- tests/system-tests/rdscore/tests/00_validate_top_level.go
Revert "system-test: remove RBD deployment pre-requisite (#42)"
This reverts commit 9b86c03c84cf734ebc8bf87f809b12cc0882b493.
Deploy workload with RBD volume to be used in post reboot tests.
> system-test: deploy workload with RBD volumes

- go.mod
- go.sum
- tests/system-tests/internal/await/await.go
- tests/system-tests/vcore/internal/config-files/clo-instance.yaml
- tests/system-tests/vcore/internal/config-files/keda-test-app-load-job.yaml
- tests/system-tests/vcore/internal/vcorecommon/esk-clo-operator.go
- tests/system-tests/vcore/internal/vcorecommon/helper.go
- tests/system-tests/vcore/internal/vcorecommon/initial-platform-deployment.go
- tests/system-tests/vcore/internal/vcorecommon/keda-validation.go
- tests/system-tests/vcore/internal/vcorecommon/metallb-operator.go
- tests/system-tests/vcore/internal/vcorecommon/nmstate-validation.go
- tests/system-tests/vcore/internal/vcorecommon/node-tuning-operator.go
- tests/system-tests/vcore/internal/vcorecommon/numa-operator.go
- tests/system-tests/vcore/internal/vcorecommon/post-deployment-config.go
- tests/system-tests/vcore/internal/vcorecommon/smo-validation.go
- tests/system-tests/vcore/internal/vcoreconfig/config.go
- tests/system-tests/vcore/internal/vcoreparams/const.go
- tests/system-tests/vcore/tests/00_validate_basic_deployment.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/nrop/nrop.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/nrop/nropscheduler.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/nto/performanceprofile.go
- vendor/modules.txt
> vCore: numa test suite

- tests/system-tests/ran-du/internal/randuconfig/config.go
- tests/system-tests/ran-du/internal/randuconfig/default.yaml
- tests/system-tests/ran-du/tests/hard-reboot.go
- tests/system-tests/ran-du/tests/kernel-crash-kdump.go
- tests/system-tests/ran-du/tests/launch-workload-multiple-iter-loadavg.go
- tests/system-tests/ran-du/tests/launch-workload.go
- tests/system-tests/ran-du/tests/soft-reboot.go
- tests/system-tests/ran-du/tests/stability-no-workload.go
- tests/system-tests/ran-du/tests/stability-workload.go
Also, include small improvements like customize reboot
recovery time. Also, fixes the stability output file
between two different tests
> system-test: Enable ptp checks in existing test cases

- tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/rollback-after-failed-upgrade-test.go
Currently the test panicks with the following error:
runtime error: invalid memory address or nil pointer dereference
This change initializes the AutoRollbackOnFailure structure before setting the AutoRollbackOnFailure value.
```
STEP: Setting LCA init-monitor watchdog timer to 5 minutes - /home/marius/git/eco-gotests/tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/rollback-after-failed-upgrade-test.go:54 @ 07/02/24 10:46:45.281
END STEP: Retrieve seed image version and updating LCA init-monitor watchdog timer  - /home/marius/git/eco-gotests/tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/rollback-after-failed-upgrade-test.go:48 @ 07/02/24 10:46:45.281 (318ms)
[PANICKED] Test Panicked
In [BeforeEach] at: /usr/local/go/src/runtime/panic.go:261 @ 07/02/24 10:46:45.281
runtime error: …
```
> lca: cnf: fix rollback-after-failed-upgrade-test

- tests/cnf/ran/powermanagement/internal/helper/helper.go
- tests/cnf/ran/powermanagement/tests/cpufreq.go
- This PR adds an OCP version check to the Reserved Core Freqency Tuning test, ensuring it only runs on OCP 4.16 or greater.
- CompareOCPVersionWithCurrent() was moved from  tests/system-tests/internal/platform/platform.go to tests/internal/cluster/config.go so it could be imported into tests/cnf/ran/tests
- tests/system-tests/vcore/internal/vcorecommon/cgroup-operator.go was updated to reflect the new location of CompareOCPVersionWithCurrent()
- Finally, a bug was found and fixed in CompareOCPVersionWithCurrent(). Previously, in the case where isGreater=true and the check failed, the LessThan function would still run and the function would return true erroneously. Essentially the function was testing for both greater than and less than at the same time.  I added an if !greater block …
> Add Version Check to Reserved Core Freqency Tuning Test. Fix and move CompareOCPVersionWithCurrent() 

- tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/e2e-upgrade-test.go
- tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/prep-abort-test.go
- tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/rollback-after-failed-upgrade-test.go
- tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/upgrade-abort-test.go
After the finalize CGU reports Completed state wait for the IBU Idle condition to report True as well. Also remove 'Wait until node is reporting as Ready' as it can sometimes prematurely fail if the kube api is not available.  In addition wait 10 seconds after the CGUs deletion as it seems that if we delete and re-create the CGUs too quickly the policies do not have enough time to reconciliate their status.
> lca: cnf: wait for ibu idle stage after finalize cgu

- tests/system-tests/internal/stability/stability.go
- tests/system-tests/ran-du/tests/stability-no-workload.go
- tests/system-tests/ran-du/tests/stability-workload.go
In order to catch issues such as [OCPBUGS-30813 ](https://issues.redhat.com/browse/OCPBUGS-30813)add a check to the stability test which validates that tuned does not continuously apply its configuration.
> system-tests: ran-du: add tuned restarts check to stability tests

- tests/cnf/ran/powermanagement/internal/helper/helper.go
- tests/cnf/ran/powermanagement/tests/cpufreq.go
- tests/cnf/ran/powermanagement/tests/powersave.go
The powersave test cases would pipe the output from cat into `cat -` which causes errors to be ignored as a workaround for ocassional malformed output. This has been converted to us Eventually to allow for retrying on malformed output.
> cnf ran: remove cat hack from powersave

- tests/cnf/ran/talm/tests/talm-backup.go
- tests/cnf/ran/talm/tests/talm-batching.go
- tests/cnf/ran/talm/tests/talm-blockingcr.go
- tests/cnf/ran/talm/tests/talm-precache.go
TALM test cases needed to be revised to remove duplicate test IDs. New polarion test cases were added where needed. Others were merged. Full details of Polarion changes are in each subtask of CNf-12600
> Revise Polarion Test Case IDs in TALM tests

- tests/cnf/ran/talm/internal/tsparams/consts.go
- tests/cnf/ran/talm/internal/tsparams/talmvars.go
- tests/cnf/ran/talm/talm_suite_test.go
- tests/internal/reporter/reporter.go
Currently, the cnf/ran test suites do not log the CRs used in each test case, which becomes particularly important for the TALM and ZTP test suites. This PR uses the existing infrastructure in the repo around reporting to generate dumps with these resources.
There is an additional function in the internal/reporter package that allows reports to dump the CRs from a specific kubeconfig, not just the one specified by the KUBECONFIG environment variable.
> cnf ran: add reporting for CRs on each cluster

- tests/cnf/ran/internal/ranparam/const.go
- tests/cnf/ran/ztp/tests/ztp-generator.go
Testing the ZTP generator tests in the actual environment revealed that the output from brew was not handled properly. This PR adds a sed command to retrieve the version tag from the output.
Additionally, the no-container label is added for tests that should not be executed in a container, such as ztp-generator currently.
> cnf ran: ztp generator tweaks based on testing

- tests/cnf/ran/ztp/internal/helper/policiesapp.go
- tests/cnf/ran/ztp/internal/tsparams/consts.go
- tests/cnf/ran/ztp/tests/ztp-argocd-hub-templating.go
This adds the secret creation to the code for the hub templating test rather than letting it be created by Argo CD since that is not permitted.
It additionally fixes an issue that has occured with the image registry object being nil.
> cnf ran: add secret creation to ztp hub templating

- tests/assisted/ztp/operator/tests/aci-dualstack-ipv4-first.go
- tests/assisted/ztp/operator/tests/build-artifacts-rootfs.go
- tests/assisted/ztp/operator/tests/infraenv-multiarch-image.go
- tests/assisted/ztp/operator/tests/osimage-clusterimageset-test.go
Adds test namespace created during operator test suite to reporter in order to dump CRs for failed tests
> assisted ztp: add operator suite test namespaces to reporter

- tests/cnf/ran/ztp/internal/tsparams/ztpvars.go
- tests/cnf/ran/ztp/tests/ztp-argocd-hub-templating.go
- tests/cnf/ran/ztp/tests/ztp-argocd-policies-app.go
- tests/cnf/ran/ztp/ztp_suite_test.go
1. Reporting for the custom resources has been added to the ZTP test suite. The caveat is that until eco-goinfra support is added it will be missing the Argo CD Applications CR.
2. Image registry tests have been changed a bit to test for the path in git before failing if /var/imageregistry is not present.
3. An additional log has been added to the hub templating tests to provide more information for a failure that ocurred in CI.
> cnf ran: ztp reporting and improvements

- tests/accel/internal/accelconfig/config.go
- tests/accel/internal/accelconfig/default.yaml
- tests/accel/internal/accelinittools/accelinittools.go
- tests/accel/internal/accelparams/const.go
- tests/accel/upgrade/internal/createres/create.go
- tests/accel/upgrade/internal/deleteres/delete.go
- tests/accel/upgrade/internal/upgradeparams/const.go
- tests/accel/upgrade/internal/upgradeparams/vars.go
- tests/accel/upgrade/tests/upgrade.go
- tests/accel/upgrade/upgrade_suite_test.go
> accel: add ocp upgrade test

- tests/cnf/ran/ztp/internal/tsparams/ztpvars.go
- tests/cnf/ran/ztp/tests/ztp-spoke-checker.go
1. The list of spoke CRs to report for the ZTP suite test is currently missing the image registry config despite this CR being used in the policies app test.
2. The spoke checker test currently assumes that the cluster is SNO which causes it to fail for SNO+1. This PR updates it to perform the check on each node.
> cnf ran: image registry CR report and spoke checker fix

- tests/cnf/ran/talm/tests/talm-backup.go
TALM backup has been deprecated starting from 4.16, so this PR disables them in tests for deprecated versions.
> cnf ran: disable talm backup tests for 4.16+

- tests/assisted/ztp/operator/tests/additional-trust-bundle.go
- tests/assisted/ztp/operator/tests/platform-selection-test.go
These tests have been flaky recently but collected info always looks as expected. Increasing timeouts to hopefully remediate these failures.
> assisted ztp: increase timeouts for platform and trustbundle tests

- tests/system-tests/internal/reboot/reboot.go
- tests/system-tests/ran-du/tests/kernel-crash-kdump.go
evaluate _OpenShift API server_ availability outside of *KernelCrashKdump* function
> system-test: refactor KernelCrashKdump function

- tests/system-tests/rdscore/internal/rdscorecommon/ipvlan-validation.go
- tests/system-tests/rdscore/internal/rdscoreconfig/config.go
- tests/system-tests/rdscore/internal/rdscoreconfig/default.yaml
With static address assignment it's required to have a dedicated _NAD_ per workload
> system-test: use dedicated IPVLAN NADs per test

- tests/cnf/ran/talm/internal/helper/cgu.go
- tests/cnf/ran/talm/internal/helper/cluster.go
- tests/cnf/ran/talm/internal/mount/mount.go
- tests/cnf/ran/talm/internal/setup/cleanup.go
- tests/cnf/ran/talm/internal/setup/setup.go
- tests/cnf/ran/talm/internal/tsparams/talmvars.go
- tests/cnf/ran/talm/talm_suite_test.go
- tests/cnf/ran/talm/tests/talm-backup.go
- tests/cnf/ran/talm/tests/talm-batching.go
- tests/cnf/ran/talm/tests/talm-blockingcr.go
- tests/cnf/ran/talm/tests/talm-canary.go
- tests/cnf/ran/talm/tests/talm-precache.go
* Reorganize talm/internal/helper into three different, more-specific packages.
* Switch to eco-goinfra functions where available, such as waiting for CGU conditions.
* Some other minor refactorings, like removing the unnecessary loop in `helper.DoesClusterLabelExist`.
> cnf ran: reorganize talm helpers

- tests/cnf/ran/powermanagement/powermanagement_suite_test.go
In the powermanagement test suite, there is a failure due to the stressng pods not meeting the restricted security standard. This updates the namespace to only enforce the baseline standard, which should allow the stressng pods to be created.
> cnf ran: update pod security label for test namespace

- tests/cnf/ran/gitopsztp/internal/nodedelete/nodedelete.go
- tests/cnf/ran/gitopsztp/tests/ztp-argocd-acm-crs.go
- tests/cnf/ran/gitopsztp/tests/ztp-argocd-clusters-app.go
- tests/cnf/ran/gitopsztp/tests/ztp-argocd-hub-templating.go
- tests/cnf/ran/gitopsztp/tests/ztp-argocd-node-delete.go
- tests/cnf/ran/gitopsztp/tests/ztp-argocd-policies-app.go
- tests/cnf/ran/gitopsztp/ztp_suite_test.go
- tests/cnf/ran/internal/rancluster/rancluster.go
- tests/cnf/ran/internal/ranconfig/config.go
- tests/cnf/ran/internal/ranhelper/ranhelper.go
- tests/cnf/ran/internal/version/version.go
- tests/cnf/ran/internal/version/version_test.go
- tests/cnf/ran/powermanagement/tests/cpufreq.go
- tests/cnf/ran/talm/internal/helper/cluster.go
- tests/cnf/ran/talm/tests/talm-backup.go
- tests/cnf/ran/talm/tests/talm-batching.go
- tests/cnf/ran/talm/tests/talm-blockingcr.go
- tests/cnf/ran/talm/tests/talm-canary.go
- tests/cnf/ran/talm/tests/talm-precache.go
* Moves version testing into its own package.
* Creates a new rancluster package for cluster-level utilities, such as checking if it is SNO+1.
* Updates the test suites to use these new packages.
> cnf ran: cnf/ran/internal reorganization

- tests/assisted/ztp/operator/tests/platform-selection-test.go
Currently our tests leverage Wait methods which prevent us from capturing actual vs expected behavior. This PR updates the platform-selection tests to use the Eventually container and compare condition message directly.
> assisted ztp: use eventually in platform tests

- tests/assisted/ztp/operator/tests/aci-dualstack-ipv4-first.go
- Increases timeout in dual stack test to 2 minutes
- Changes assertion to use Eventually rather than Wait
> assisted ztp: increase timeout in dualstack test

- tests/cnf/core/network/dpdk/dpdk_suite_test.go
- tests/cnf/core/network/sriov/tests/qinq.go
- PerfProf name to match with sriov test suite.
- Remove Deleting PerfProf after test execution.
> cnf network: performance profile - remove repetition

- tests/cnf/ran/README.md
- tests/cnf/ran/gitopsztp/internal/tsparams/consts.go
- tests/cnf/ran/gitopsztp/tests/ztp-bios-day-zero.go
ZTP BIOS test added: Compare requested BIOS settings to current BIOS settings
> cnf ran: add ZTP verify BIOS settings test case

- tests/lca/imagebasedupgrade/cnf/internal/validations/post_ibu_validations.go
when there are no images returned grep command exits with rc 1 and the ExecCmdWithStdout is failing before evaluating the output
> lca cnf: fix ValidateNoImagesPulled post ibu validation

- tests/cnf/ran/internal/ranconfig/default.yaml
- tests/cnf/ran/talm/tests/talm-precache.go
There is currently a test case in the TALM suite that is always skipped due to the inputs being wrong. This PR switches it to use a regex that will work in newer versions.
> cnf ran: update skipped talm test case

- tests/cnf/core/network/internal/netnmstate/netnmstate.go
Fixing  the issue https://github.com/openshift-kni/eco-gotests/issues/207
Latest knmstate is using openshift cert service, so no cert manager pod is needed
> cnf-network: changed func isNMStateDeployedAndReady

- tests/cnf/core/network/day1day2/tests/day1day2.go
- tests/cnf/core/network/internal/netconfig/config.go
- tests/cnf/core/network/internal/netnmstate/netnmstate.go
- tests/cnf/core/network/sriov/tests/externalllymanaged.go
Updated the existing Day 1/Day 2 and exmanaged tests due to changes in the Day 1 cluster configuration—VLAN will now be configured directly on the VF instead of through the interface VLAN.
> cnf-network: Adjusted day1day2 sriov and exmanaged tests

- .github/workflows/eco-goinfra-bump.yml
The error from the previous [run](https://github.com/openshift-kni/eco-gotests/actions/runs/11000202120/job/30542074725):
```
Run echo "" > ~/.ssh/eco-gotests.id_rsa
/home/runner/work/_temp/9ab6dc9e-92[7](https://github.com/openshift-kni/eco-gotests/actions/runs/11000202120/job/30542074725#step:3:8)5-4f77-8a12-e4f64975a9ee.sh: line 1: /home/runner/.ssh/eco-gotests.id_rsa: No such file or directory
```
Just making sure that the directory and file exist prior to sending the REPO_ACCESS_KEY contents to the file.
> ci: ensure id_rsa file exists

- tests/cnf/core/network/sriov/tests/metricsExporter.go
- Create SriovNodePolicies together
- Clear ARP table on switch before executing each Vfio test case
- Increase wait time @line449 for flaky scenarios
> cnf network: Fix sriovmetrics Tests on Intel NICs

- tests/cnf/core/network/sriov/tests/qinq.go
THe regex QinQ pattern doesnt match this entry
`  16:48:21.297032 b6:fe:74:3a:e3:88 (oui Unknown) > 33:33:00:00:00:02 (oui Unknown), ethertype 802.1Q (0x8100), length 78: vlan 179, p 0, ethertype 802.1Q (0x8100), vlan 100, p 0, ethertype IPv6 (0x86dd), fe80::b4fe:74ff:fe3a:e388 > ff02::2: ICMP6, router solicitation, length 16`
> cnf-network: changed regex pattern in QinQ test

- tests/cnf/core/network/metallb/internal/frr/frr.go
- tests/cnf/core/network/metallb/internal/tsparams/consts.go
- tests/cnf/core/network/metallb/internal/tsparams/mlbvars.go
- tests/cnf/core/network/metallb/tests/bfd-test.go
- tests/cnf/core/network/metallb/tests/bgp-connect-time-tests.go
- tests/cnf/core/network/metallb/tests/bgp-tests.go
- tests/cnf/core/network/metallb/tests/common.go
- tests/cnf/core/network/metallb/tests/frrk8-tests.go
- tests/cnf/core/network/metallb/tests/layer2-test.go
Add 7 of the 9 test cases for epic metallb-frrk8
> cnf network: add ffrk8 metallb test cases

- tests/cnf/core/network/metallb/internal/prometheus/prometheus.go
The issue is that all MetalLB metrics in the frr-k8s pod now have a new prefix frrk8s_, whereas the old prefix was metallb_. When querying in Prometheus, it fails to find the new frrk8s_ prefix, while the old metallb_ prefix still works.
```
sh-5.1$ curl "http://localhost:9090/api/v1/query?query=frrk8s_bfd_control_packet_input"
{"status":"success","data":{"resultType":"vector","result":[]}}
```
```
sh-5.1$ curl "http://localhost:9090/api/v1/query?query=metallb_bfd_control_packet_input"
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"metallb_bfd_control_packet_input","container":"kube-rbac-proxy-frr","endpoint":"frrmetricshttps","instance":"10.46.73.2:9141","job":"frr-k8s-monitor-service","namespace":"metallb-system","peer":"10.46.73.131","pod":"frr-k8s-pg …
```
> cnf-network: adjusted metallb metric tests

- tests/cnf/core/network/sriov/tests/qinq.go
This line is not matched
`23:39:46.630721 4a:9a:74:4e:e3:ae (oui Unknown) > 92:92:b1:91:ae:c5 (oui Unknown), ethertype 802.1Q-QinQ (0x88a8), length 194: vlan 175, p 0, ethertype 802.1Q (0x8100), vlan 101, p 0, ethertype IPv6 (0x86dd), 2001:100::1.57854 > 2001:100::2.krb524: Flags [P.], seq 301:401, ack 301, win 259, options [nop,nop,TS val 3871989833 ecr 1959490438]`
> cnf-network: changed 101 Vlan regex in QinQ tests

- tests/cnf/core/network/metallb/internal/tsparams/mlbvars.go
- tests/cnf/core/network/metallb/tests/common.go
- tests/cnf/core/network/metallb/tests/frrk8-tests.go
Last two test cases of frrk8 epic
> cnf network: add-metallb-frr-test-cases

- tests/cnf/core/network/sriov/tests/rdmametrics.go
MCP update is happening ~12 seconds while deleting an MC
> cnf network: fix rdma flake

- tests/cnf/core/network/metallb/tests/common.go
This pull request addresses an issue with traffic validation during MetalLB testing. Currently, the client test pod is able to reach the server through the default route because it runs on a master node. This setup results in false positive validation results.
> cnf-network:metallb: removed default route from the frr test container

- tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/e2e-upgrade-test.go
Currently the step is failing with
```
16:17:02    END STEP: Deleting upgrade ibgu created on target hub cluster - /home/testuser/tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/e2e-upgrade-test.go:54 @ 10/15/24 13:16:55.544 (0s)
16:17:02    [FAILED] Failed to delete prep-upgrade ibgu on target hub cluster
16:17:02    Unexpected error:
16:17:02        <*errors.errorString | 0xc001013240>: 
16:17:02        error: received nil ibgu builder
16:17:02        {
16:17:02            s: "error: received nil ibgu builder",
16:17:02        }
16:17:02    occurred
16:17:02    In [AfterAll] at: /home/testuser/tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/e2e-upgrade-test.go:56 @ 10/15/24 13:16:55.544
16:17:02    < Exit [AfterAll] Performing happy path image based upgrade - …
```
> lca cnf: fix missing ibgu builder during e2e afterall

- tests/cnf/ran/gitopsztp/tests/ztp-cluster-instance-delete.go
Found out that this can fail in CI sometimes when the test case isn't applicable anyway. This PR just allows the AfterEach to be skipped when these tests do not apply, preventing the errors from appearing in CI. It does this by only running the AfterEach once changes are made to need it.
> cnf ran: clusterinstance skip aftereach when not needed

- tests/cnf/ran/gitopsztp/internal/tsparams/consts.go
- tests/cnf/ran/gitopsztp/internal/tsparams/ztpvars.go
- tests/cnf/ran/gitopsztp/tests/ztp-siteconfig-failover.go
Hello @klaskosk , @dgonyier , @josclark42.
Please help to review this PR when you have a time. Thanks!
Adding siteconfig operator failover test cases
[OCP-75382](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-75382)
[OCP-75383](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-75383)
Manual Test Logs:
https://docs.google.com/document/d/1mX-Pbs7affHaD3qGeuy4nHr5ppPoFH1F-laRAO9nchU/edit?usp=sharing
> cnf ran: Add siteconfig operator failover tests

- tests/cnf/core/network/metallb/tests/frrk8-tests.go
Back port fix of metallb frrk8 test case label. Was not being deleted.
> cnf network: fix-metallb-frrk8-test-label

- tests/cnf/ran/gitopsztp/internal/tsparams/consts.go
- tests/cnf/ran/gitopsztp/internal/tsparams/ztpvars.go
- tests/cnf/ran/gitopsztp/tests/ztp-siteconfig-negative.go
Hello @klaskosk , @dgonyier , @josclark42.
Please help to review this PR when you have a time. Thanks!
Adding siteconfig operator negative test cases
[OCP-75378](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-75378)
[OCP-75379](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-75379)
Manual Test Logs:
[1]
https://docs.google.com/document/d/1goaT3l0-tPacJQN46xVyw68g2PtlkuTPVaEIoVHCVVA/edit?usp=sharing
[2]
https://docs.google.com/document/d/11-LXu9Krf-4UczKBmh_9vN1fKqNr74l8s4WFD3M7tCc/edit?usp=sharing
> cnf ran: Add siteconfig operator negative tests

- tests/cnf/ran/gitopsztp/internal/helper/helper.go
- tests/cnf/ran/gitopsztp/internal/tsparams/consts.go
- tests/cnf/ran/gitopsztp/tests/ztp-siteconfig-day-two.go
- tests/cnf/ran/internal/rancluster/rancluster.go
Hello @klaskosk , @dgonyier , @josclark42.
Please help to review this PR when you have a time. Thanks!
Adding siteconfig operator day-two test case.
[OCP-75342](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-75342)
Manual Test Logs:
https://docs.google.com/document/d/145d7cctxZwmvKepNiaZw2v3cQtezCCPHXjQ3r6ySCZM/edit?usp=sharing
Test automation code validation logs:
https://docs.google.com/document/d/1aP028ofPtOZnL7ju21EZyCD0NQhMAF1gUtQFU9ZE-Jg/edit?usp=sharing
> cnf ran: Add siteconfig operator day-two test

- tests/rhwa/internal/rhwaparams/const.go
Default namespace for RHWA operators was changed to "openshift-workload-availability". Fixed default namespace in tests to align to existing default value.
> Fix default namespace for RHWA operators tests

- tests/cnf/core/network/metallb/tests/frrk8-tests.go
According to the latest changes, timers should only be modified in the BgpPeer CR, not in frrconfig.
> cnf-network: removed timers configuration from the frrconfig CR

- tests/rhwa/far-operator/tests/far.go
- tests/rhwa/internal/dast/config-files/rapidastConfig.yaml
- tests/rhwa/internal/dast/dast.go
- tests/rhwa/internal/rhwaparams/const.go
Adds a test that runs rapidast scan for the FAR operator installed in the cluster.
It configures the rapidast for the execution of the trivy scan, looking for misconfigurations on the pods running on the namespace where the operator is installed.
The test fails if any High severity vulnerability is found, providing in the console output the details of the detection.
> rhwa: DAST test on FAR operator

- tests/lca/imagebasedinstall/mgmt/deploy/internal/networkconfig/networkconfig_types.go
- tests/lca/imagebasedinstall/mgmt/deploy/tests/e2e-deploy-test.go
- tests/lca/imagebasedinstall/mgmt/internal/mgmtconfig/config.go
- Add configuration parameter for enabling static networking when configuring spoke
- Add networkconfig pkg to help generate static network configurations
- Add static network configuration to deploy test
> ibi mgmt: add static network configuration to IBI deploy test

- tests/cnf/core/network/metallb/tests/frrk8-tests.go
backport of https://github.com/openshift-kni/eco-gotests/pull/267
> cnf network: remove timers from frrconfig CR

- .github/workflows/eco-goinfra-bump.yml
Tested on my own repo, it won't break the CI run even if it can't add the reviewers (which it couldn't since not everyone is a contributor on my fork).
> ci: add reviewers to eco-goinfra bumps

- tests/cnf/core/network/metallb/tests/frrk8-tests.go
Fix for issue https://github.com/openshift-kni/eco-gotests/issues/266
> cnf network: fix frrnodestatus test case

- tests/system-tests/rdscore/internal/rdscorecommon/metallb-graceful-restart.go
prevent log clutter by changing logging level
> system-test: limit logging for Graceful Restart tests

- tests/cnf/ran/gitopsztp/internal/tsparams/ztpvars.go
- tests/internal/reporter/schemes.go
In the reporter package, this adds the certificatesv1 schema to the client for reporting.
In the cnf/ran/gitopsztp package, this adds the CertificateSigningRequest to the list of spoke CRs to dump on test failure.
> reporter,cnf ran: add CSRs to spoke resources reported

- tests/cnf/ran/internal/rancluster/rancluster.go
- tests/cnf/ran/talm/tests/talm-precache.go
* When turning off the spoke, wait until the BMC reports it is off before continuing.
* Similarly, wait until the BMC reports it is on before continuing.
* Fixing the instability in AfterAll will require an eco-goinfra change.
* Tested on my env.
> cnf ran: increase talm precache stability

- tests/assisted/ztp/operator/internal/tsparams/operatorvars.go
- tests/assisted/ztp/operator/tests/https-webserver-setup-test.go
- Add pods to reporter in operator test suite
- Add httpdtest namespace to reporter for debugging failures
> assisted ztp: add https-webserver test namespace pods to report dump

- tests/cnf/core/network/policy/internal/tsparams/consts.go
- tests/cnf/core/network/policy/internal/tsparams/policyvars.go
- tests/cnf/core/network/policy/tests/common.go
- tests/cnf/core/network/policy/tests/multinetpolicy_ipvlan.go
`multinetpolicy_ipvlan.go` Multi-NetworkPolicy IPVLAN CNI Tests
> cnf-network: add multi-netpolicy tests for ipvlan cni

- tests/lca/imagebasedinstall/mgmt/deploy/tests/e2e-deploy-test.go
This helps in debugging issues discovered with ipv6
> Adding a testing scenario for add-hoc test

- .golangci.yml
- tests/internal/config/config.go
- tests/internal/config/default.yaml
- tests/internal/systemreporter/systemreporter.go
- Adds systemreporter pkg
- Adds ability to gather command output from machine under test through kube-api 
- Adds ability to gather command output from machine under test through ssh connection
- Adds ECO_SSH_KEY_PATH and ECO_SSH_USER to GeneralConfig in order to to provide SSH access to nodes under test
> infra: add systemreporter pkg

- tests/cnf/ran/gitopsztp/internal/tsparams/consts.go
- tests/cnf/ran/gitopsztp/internal/tsparams/ztpvars.go
- tests/cnf/ran/gitopsztp/tests/ztp-argocd-policies-app.go
- tests/cnf/ran/gitopsztp/ztp_suite_test.go
* Add a workaround for an issue where the policy definition would be nil. Failures only commonly occur during this ocm.PullPolicy specifically so a workaround here is sufficient.
* Switches the custom source CR service account namespace to the test namespace which requires creating the namespace on the spoke too.
* Change to recreating the test namespace per test case rather than per suite. This should improve the isolation between tests and fix some of the automation issues related to namespaces.
> cnf ran: fix ZTP suite automation issues

- tests/system-tests/diskencryption/tests/tpm2.go
In latest tests (new dell platform), reading swapped boot order seems to return wrong value (not swapped) on second boot but looks correct in the bios. So if just reading and swapping back the boot order with lead to no changes (e.g. not swapped -> swapped again).
Instead of reading latest boot order and swapping back and forth, back up original boot order and restore it after testing with swapped boot order.
> save original boot order instead of reading current value and swapping when recovering

- tests/cnf/core/network/sriov/tests/metricsExporter.go
- tests/cnf/core/network/sriov/tests/paralleldraining.go
- tests/cnf/core/network/sriov/tests/rdmametricsapi.go
- Parallel Draining: Added NAD creation checkpoint to prevent flaky [issues](https://jenkins-csb-kniqe-auto.dno.corp.redhat.com/job/ocp-eco-gotests/2147//testReport/junit/(root)/sriov/_It__ParallelDraining_without_SriovNetworkPoolConfig__paralleldraining__68640__test_id_68640_/)
- Sriov Metrics Exporter: Use VendorID instead of DeviceID (as it failed on [cluster14](https://jenkins-csb-kniqe-auto.dno.corp.redhat.com/job/ocp-eco-gotests/2147/testReport/(root)/sriov/))
- Rdma metrics API: Specific error messages added. eco-goinfra [PR](https://github.com/openshift-kni/eco-goinfra/pull/891) for CleanObjects is merged.
> cnf network: fix test issues

- tests/system-tests/rdscore/internal/rdscorecommon/egress-service.go
Enhance the test by checking it was properly processed by the OVN and has node assigned
> system-test: assert EgressService status after creation

- tests/system-tests/rdscore/internal/rdscorecommon/sriov-validation.go
(cherry picked from commit 45906c7fd971b757678aeb894b79df78dbec91a0)
> system-test: drop extra sleep for SR-IOV tests

- .github/workflows/eco-goinfra-bump.yml
- .github/workflows/makefile.yml
- Dockerfile
- go.mod
[Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2609](https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2766)
> Update Go to v1.23.6

- tests/system-tests/rdscore/internal/rdscorecommon/egress-ip.go
After node is rebooted it takes some time for the pod to start hence extra check is added to ensure pod is `Ready` before trying to execute commands from it.
> system-test: wait for pod to be ready for EgressIP test

- tests/lca/imagebasedinstall/mgmt/deploy/tests/e2e-deploy-test.go
- tests/lca/imagebasedinstall/mgmt/internal/mgmtconfig/config.go
The validation includes the presence and size
of the partition provided via argument
> lca ibi: add validation for extra partition

- .github/dependabot.yml
This PR just copies the dependabot config Brandon added in openshift-kni/eco-goinfra#240 to keep our actions up to date.
> infra: add actions dependabot

- .github/workflows/eco-goinfra-bump.yml
- .github/workflows/makefile.yml
This PR updates the eco-goinfra-bump workflow to call the CI workflows and label the bump PR accordingly.
[Example action run](https://github.com/klaskosk/eco-gotests/actions/runs/13291564282)
[Example PR](https://github.com/klaskosk/eco-gotests/pull/7)
> infra: call CI from eco-goinfra bump

- Makefile
`GO111MODULE` is no longer needed and was deprecated in Go 1.16 and the flag is completely ignored in Go 1.17.
https://go.dev/blog/go116-module-changes
> Remove GO111MODULE flag

- tests/system-tests/rdscore/internal/rdscorecommon/egress-ip.go
Invoked command has a timeout of 5 seconds, `--connect-timeout 5`, therefor extending timeout of the retry block to 1 minute
> system-test: increase timeout while executing command

- tests/assisted/ztp/internal/ztpconfig/config.go
- tests/assisted/ztp/internal/ztpinittools/ztpinittools.go
- Updates ztpinittools to collect hub API client from ZTPConfig rather than through inittools directly
- Helps in recovering from errors during hub environment initialization
> assisted ztp: get hub API client through ZTPConfig

- tests/system-tests/rdscore/internal/rdscorecommon/egress-service.go
- tests/system-tests/rdscore/internal/rdscoreconfig/config.go
- tests/system-tests/rdscore/internal/rdscoreconfig/default.yaml
- tests/system-tests/rdscore/tests/00_validate_top_level.go
* system-test: VerifyEgressServiceETPClusterWrapper method added
* system-test: VerifyEgressServiceWithClusterETPNetwork method added
* system-test: refactored verifyPodSourceAddress and verifySourceIP
* system-test: adjusted verifyPodSourceAddress method
* system-test: VerifyEgressServiceConnectivityETPClusterSourceIPByNetwork added
* system-test: VerifyEgressServiceWithLocalETPWrapper added
* system-test: VerifyEgressServiceWithLocalETPSourceIPByNetwork added
* system-test: VerifyEgressServiceWithLocalETPSourceIPByNetwork modified
* system-test: skip tests if EgressServiceNetworkExpectedIPs not defined
* system-test: ingress tests added
> system-test: EgressService tests with sourceIPBy=Network added

- tests/cnf/ran/talm/internal/setup/setup.go
- tests/internal/cluster/cluster.go
This is part 1 of a 3 part effort to replace pod.WaitForAllPodsInNamespacesHealthy.
1. (openshift-kni/eco-goinfra#928) Add new helpers to eco-goinfra that simplify waiting for pods healthy and list on every iteration.
2. (This PR) Change the cluster.WaitForRecover function to use the new eco-goinfra helpers. Also a small change in cnf/ran/talm.
3. Remove the old helpers from eco-goinfra.
Motivation:
The old WaitForRecover function would list the pods each iteration, ensuring that pods started after calling the function will be checked as well as ignoring pods that later end up deleted. A workaround for the latter of these issues was merged in openshift-kni/eco-goinfra#808.
Additionally, the current pod.WaitForAllPodsInNamespacesHealthy has too many parameters and is hard to test properly. …
> global: update WaitForRecover to use new method

- tests/system-tests/rdscore/internal/rdscorecommon/egress-ip.go
When invoking _verifyEgressIPFailOver_ method pass its _isIPv6_ parameter to the inner call to `getNodeForReboot` method.
So when testing IPv6 failover node that holds IPv6 address of _EgressIP CR_ is used
At the same time added extra logging to make troubleshooting easier.
> system-test: use node that holds IPv6 EgresIP address

- .golangci.yml
The console currently prints the following on every `make lint`:
```
WARN [config_reader] The configuration option `run.skip-dirs-use-default` is deprecated, please use `issues.exclude-dirs-use-default`.
WARN [config_reader] The configuration option `output.format` is deprecated, please use `output.formats`
WARN [config_reader] The configuration option `linters.stylecheck.go` is deprecated, please use global `run.go`.
WARN [lintersdb] The linter "structcheck" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
```
This PR fixes these issues as well as addresses all of the other places the config deviates from the schema. None of the settings for the `unused` linter were actual …
> lint: fix errors and warnings in golangci-lint config

- tests/cnf/ran/oran/tests/oran-post-provision.go
- tests/cnf/ran/oran/tests/oran-pre-provision.go
In certain tests, the prBuilder is set then used again in AfterEach without being pulled again. When the test fails calling a function that sets prBuilder, this can lead to prBuilder being set to nil with no way to clean up after the tests. This PR addresses the issue by always pulling prBuilder in the AfterEach block.
> cnf ran: fix edge case that causes nil prBuilder

- tests/cnf/ran/oran/internal/helper/helper.go
- tests/cnf/ran/oran/tests/oran-post-provision.go
There are a few lingering automation issues caused by race conditions between the tests and the operator on the cluster. This PR addresses them in two ways:
1. Adds a sleep to 77374. This is a bit of a workaround but for now the simplest way to ensure that we do not end up in the situation where a policy template is updated but its compliance state refers to the old template.
1. Adds an additional step to waitForPolicies which ensures that the policy details in the ProvisioningRequest status match the desired policy version. Previously, we could end up in a situation where all the policies have propagated to the spoke but the ProvisioningRequest shows the old policies. This would then cause a 403 as the ProvisioningRequest turns pending after the policies have propagated and the state had …
> cnf ran: fix small post-provision automation issue

- tests/cnf/core/network/internal/netparam/netvars.go
- tests/cnf/core/network/metallb/internal/frr/frr.go
- tests/cnf/core/network/metallb/internal/metallbenv/metallbenv.go
- tests/cnf/core/network/metallb/internal/tsparams/consts.go
- tests/cnf/core/network/metallb/internal/tsparams/mlbvars.go
- tests/cnf/core/network/metallb/tests/bfd-test.go
- tests/cnf/core/network/metallb/tests/bgp-connect-time-tests.go
- tests/cnf/core/network/metallb/tests/bgp-tests.go
- tests/cnf/core/network/metallb/tests/common.go
- tests/cnf/core/network/metallb/tests/frrk8-tests.go
- tests/cnf/core/network/metallb/tests/layer2-test.go
- tests/cnf/core/network/metallb/tests/metallb-crds.go
- tests/cnf/core/network/metallb/tests/metallb-nodeSelector.go
moving test cases from cnf-gotest to eco-gotest
> add-metallb-nodeselector-tc

- tests/cnf/ran/talm/internal/tsparams/talmvars.go
In the precache tests, it is useful to know the policies not just in the test namespace, since these may be part of the talm precache policies. Additionally, the acm pod logs may have clues about what is happening with policies in the event a test fails.
> cnf ran: report more in talm suite

- tests/cnf/ran/oran/internal/tsparams/consts.go
- tests/cnf/ran/oran/internal/tsparams/oranvars.go
- tests/cnf/ran/oran/tests/oran-pre-provision.go
In preparation for the changes to automation for 4.19+, this PR removes all the ORAN test cases that are no longer necessary.
> cnf ran: remove old oran tests

- .github/workflows/eco-goinfra-integration.yml
Similar to: https://github.com/openshift-kni/eco-goinfra/pull/455 
Checks to make sure that your PR is compatible with the current version of eco-goinfra.
> ci: add eco-goinfra compatibility check

- go.mod
- tests/cnf/core/network/metallb/tests/bfd-test.go
- tests/cnf/core/network/metallb/tests/bgp-tests.go
- tests/cnf/core/network/metallb/tests/layer2-test.go
Builds on: https://github.com/openshift-kni/eco-goinfra/pull/667
Bumps the version of eco-goinfra.  `GetServiceGVR()` has been deprecated in favor of a more generic `GetGVR()` to match other functions in eco-goinfra.
> cnf core: use GetGVR() instead of GetServiceGVR()

- tests/cnf/core/network/metallb/tests/bgp-connect-time-tests.go
- tests/cnf/core/network/metallb/tests/common.go
Follow up to #209 
#209 was created way before these tests referenced the old deprecated func.
> metallb: use service.GetGVR()

- tests/accel/upgrade/internal/upgradeparams/vars.go
- tests/hw-accel/kmm/internal/kmmparams/kmmvars.go
- tests/hw-accel/kmm/mcm/tests/clamav-test.go
- tests/lca/imagebasedinstall/mgmt/deploy/tests/common.go
- tests/lca/imagebasedinstall/mgmt/deploy/tests/reinstall-test.go
- tests/lca/imagebasedupgrade/cnf/internal/validations/post_ibu_validations.go
- tests/lca/imagebasedupgrade/cnf/upgrade-talm/internal/tsparams/upgradevars.go
- tests/lca/imagebasedupgrade/mgmt/upgrade/internal/tsparams/upgradevars.go
- tests/lca/imagebasedupgrade/mgmt/upgrade/tests/e2e-upgrade-test.go
- tests/system-tests/internal/imageregistryconfig/imageregistryconfig.go
- tests/system-tests/internal/reboot/reboot.go
- tests/system-tests/internal/remote/cmd.go
- tests/system-tests/internal/stability/stability.go
- tests/system-tests/rdscore/internal/rdscorecommon/ipvlan-validation.go
- tests/system-tests/rdscore/internal/rdscorecommon/macvlan-validation.go
- tests/system-tests/spk/internal/spkcommon/setup-workloads.go
- tests/system-tests/vcore/internal/vcorecommon/post-deployment-config.go
Makes sure that imports are using a more descriptive name than `v1`.
Similar to:
- https://github.com/openshift-kni/eco-goinfra/pull/921
- https://github.com/openshift-kni/eco-goinfra/pull/239
- https://github.com/openshift-kni/eco-goinfra/pull/387
- https://github.com/openshift-kni/eco-goinfra/pull/694
- https://github.com/openshift-kni/eco-goinfra/pull/711
> Import consistency

- tests/system-tests/internal/supporttools/traceroute.go
simplify tracert and tcpdump deployment name and provide unique SA name
> System Test: RDS Core - simplify tracert and tcpdump deployment name and provide unique SA name

- .golangci.yml
- go.mod
- internal/report/cache.go
- internal/report/main.go
- internal/report/sum.go
Depends-on: #446
This PR contains the rest of the report program. It includes the last two files not part of the last PR:
* `cache.go`: Caches the trees generated from each branch and revision combination. Since a dry-run may take many minutes, caching allows the program to remain performant and responsive to changes in the templates without having to redo a dry-run.
* `main.go`: Handles the command line flags and actual running of the program. It handles retrieving values from the cache or cloning and dry running as necessary.
There are some small changes to the lint config and go.mod to allow the cache to be compressed. It uses a package already vendored so does not include additional dependencies. Compression is beneficial since the cache for the main branch alone may be over a …
> report: add rest of report program

- .github/workflows/generate-report.yml
- go.mod
- internal/report/README.md
Depends-on: #447
The final PR in the series adding the initial version of the report program, this PR adds the GitHub workflow and documentation for the report program. Once merged, all pushes will update the report using the latest version of the program and templates.
---
This is PR 4/4. An example report can be seen on [my GitHub pages](https://klaskosk.github.io/eco-gotests/report.html).
> report: add workflow and documentation

- tests/system-tests/rdscore/internal/rdscorecommon/frr-bgp.go
- tests/system-tests/rdscore/internal/rdscoreconfig/config.go
- tests/system-tests/rdscore/internal/rdscoreconfig/default.yaml
FRR pods now run on all the nodes so we need an option to filter them by node
> system-test: Filter FRR nodes per node

- tests/hw-accel/kmm/internal/get/get.go
- tests/hw-accel/kmm/modules/tests/external-registry-test.go
- tests/hw-accel/kmm/modules/tests/firmware-test.go
- tests/hw-accel/kmm/modules/tests/olm-install-test.go
- tests/hw-accel/kmm/modules/tests/signing-test.go
- tests/hw-accel/kmm/modules/tests/version-test.go
- tests/hw-accel/kmm/modules/tests/webhook-test.go
Removed the checks on operator version
Updated some timeouts
Properly return an error while looking for KMM CSVs
> hw-accel: remove csv checks for certain features in kmm tests

- tests/cnf/core/network/metallb/tests/bgp-connect-time-tests.go
backport https://github.com/openshift-kni/eco-gotests/pull/517
> cnf network: fix metallb test failure [4.17]

- tests/cnf/core/network/metallb/tests/bgp-connect-time-tests.go
backport https://github.com/openshift-kni/eco-gotests/pull/517
> cnf network: fix metallb test failure [4.18]

- tests/system-tests/rdscore/internal/rdscorecommon/sriov-validation.go
_deployment.CreateAndWaitUntilReady_  returns _nil_ and _error_ in case deployment isn't _Ready_ within requested time therefore accessing attributes like _Definition.Name_ panic:
```
[PANICKED] Test Panicked
In [It] at: /usr/local/go/src/runtime/panic.go:262 @ 04/02/25 08:30:11.477
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace
```
> system-test: fix logging issue for failed deployments

- tests/hw-accel/kmm/internal/kmmparams/kmmvars.go
- tests/hw-accel/kmm/modules/tests/taint-tolerations-test.go
This reverts commit 004d973e2999def87a97ffaeee785b508e7c3a82.
> Revert "hw-accel: add taint/tolerations tests for KMM"

- Dockerfile
- go.mod
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2899
> Update Go to v1.24.2

- tests/cnf/core/network/internal/netconfig/config.go
- tests/cnf/core/network/internal/netconfig/default.yaml
- tests/cnf/core/network/internal/netparam/const.go
- tests/cnf/core/network/metallb/internal/metallbenv/metallbenv.go
- tests/cnf/core/network/metallb/internal/prometheus/prometheus.go
- tests/cnf/core/network/metallb/internal/tsparams/consts.go
- tests/cnf/core/network/metallb/tests/bfd-test.go
- tests/cnf/core/network/metallb/tests/bgp-connect-time-tests.go
- tests/cnf/core/network/metallb/tests/bgp-remote-as-dynamic.go
- tests/cnf/core/network/metallb/tests/bgp-tests.go
- tests/cnf/core/network/metallb/tests/common.go
- tests/cnf/core/network/metallb/tests/frrk8-tests.go
- tests/cnf/core/network/metallb/tests/layer2-test.go
- tests/cnf/core/network/metallb/tests/metallb-crds.go
- tests/cnf/core/network/metallb/tests/metallb-nodeSelector.go
Changes are being implemented to metallb/frr in OCP 4.19. All frr components are being moved to a separate namespace. This PR updates existing test cases in eco-gotest to run with the new frr namespace.
> cnf network: update frr namespace

- tests/hw-accel/kmm/internal/await/await.go
- tests/hw-accel/kmm/modules/tests/external-registry-test.go
- tests/hw-accel/kmm/modules/tests/webhook-test.go
- Awaiting few seconds for the events to be published in the events tests. If still does not work, some redesign is needed
- Fixing some misspelled words in some vars
> hw-accel: fixing kmm test and some typos

- tests/hw-accel/kmm/internal/kmmparams/const.go
- tests/hw-accel/kmm/modules/internal/tsparams/kmm-vars.go
- Include `default` namespace in the reporter
- Include events in the reporter
> hw-accel: add "default" namespace and Events in KMM reporter

- .github/workflows/generate-report.yml
In switching from cache to artifacts for the cache, I did not update the action to specify the workflow run to get the cache from. Although it will not fail the workflow, this causes it to take much longer than necessary. This PR just adds a step to get the last run using the GitHub CLI.
Additionally, this switches the report to use go.mod instead of hard coding the go version. This has the effect of bumping the go version to 1.24 for generating the report.
[Example actions run](https://github.com/klaskosk/eco-gotests/actions/runs/14204272418)
> report: fix cache in action

- tests/cnf/core/network/metallb/tests/common.go
- tests/cnf/core/network/metallb/tests/metallb-nodeSelector.go
In func validatePrefix the comparsion of [] was reversed.
Expect(nextHopAddresses).To(ContainElements(workerNodesAddresses),
"Failed next hop address in not in node addresses list")
When correct this error the two nodeselector test cases failed because they passed in the incorrect number of workerNodesAddresses.
> fix metallb func validateprefix

- tests/cnf/ran/oran/internal/helper/helper.go
- tests/cnf/ran/oran/internal/tsparams/consts.go
- tests/cnf/ran/oran/tests/oran-post-provision.go
#501 missed removing the hardware profile update test case. It has already been removed from the test plan that was approved, just missed since it was part of post-provisioning file.
Additionally, the GetValidDellHwmgr function has been removed since it was dead code.
> cnf ran: remove old oran test case

- tests/cnf/core/network/metallb/internal/metallbenv/metallbenv.go
- tests/cnf/core/network/metallb/internal/tsparams/mlbvars.go
- tests/cnf/core/network/metallb/tests/common.go
- tests/cnf/core/network/metallb/tests/frrk8-tests.go
- tests/cnf/core/network/metallb/tests/metallb-crds.go
- frrk8s webhook server starts after deploying metallb instance for the first on the cluster. 1st test will fail if eco-gotests is ran right after cluster deployment. Hence, adding wait time.
- ReportIfFailed does not have correct test namespace and relevant CR/Objects to be fetched
- frrk8s test creates metallb instance twice
- use workerNodeList var instead cnfWorkerNodeList while fetching frrk8s pods. Tests fail on 3 worker node setup with this.
- remove using  cnfWorkerNodeList var everywhere else in metallb tests and use workerNodeList var only
- addlabel to the node will attempt to remove it first. This is to avoid test failures when we are trying to add a label to the node which already has the same label.
> cnf network: fix/improve metallb tests

- tests/cnf/core/network/sriov/tests/paralleldraining.go
- Sriov Operator manages dynamically `sriovnetwork.openshift.io/state` annotation on the node and while deleting test label from the node we are using stale configuration in `builder.Definition`
- Workaround is to fetch latest data before deleting test label
> cnf network: fix parallel draining

- tests/system-tests/rdscore/internal/rdscorecommon/kernel-crash-kdump.go
- tests/system-tests/rdscore/tests/00_validate_top_level.go
While testing _kdump_ some running workloads are affected by the ungraceful node shutdown and end up in _UnexpectedAdmission_ state.
This pr addresses this by filtering pods with _UnexpectedAdmission_ state that were running on the node(s) were _kdump_ was tested.
> system-test: cleanup pods affected by KDump tests

- tests/cnf/core/network/metallb/tests/bfd-test.go
- tests/cnf/core/network/metallb/tests/metallb-crds.go
Removed redundant `setLocalGWMode(false)` calls from tests as they are no longer required. This simplifies the teardown process and ensures cleaner test logic.
> cnf network: Remove unnecessary GW mode reversion calls

- tests/cnf/core/network/internal/netenv/netenv.go
- tests/cnf/core/network/metallb/tests/bfd-test.go
- tests/cnf/core/network/metallb/tests/metallb-crds.go
Updated variable names and error messages for better clarity in BFD tests. Adjusted worker node selection logic, introduced proper resource cleanup in AfterAll and AfterEach blocks, and modified timeout durations to improve test reliability. Changes ensure improved readability, maintainability, and robustness of the test suite.
> [release-4.18]cnf-network: Refactor BFD test logic and enhance error handling

- tests/cnf/core/network/internal/netparam/netvars.go
- tests/cnf/core/network/sriov/tests/qinq.go
back port - add deviceID to sriov qinq test cases
> add mlx deviceId 4.18

- tests/cnf/core/network/internal/netparam/netvars.go
- tests/cnf/core/network/sriov/tests/qinq.go
Backport - MLX connection6 deviceID added to sriov qinq test cases
> add mlx connect6 deviceID backport 4.17

- images/cnf/network/eco-gotests-network-client/Dockerfile
- tests/cnf/core/network/metallb/tests/system-metallb.go
- Update Dockerfile to handle `/clientip` `/serverip` `/hostname` `/checknet` http paths by Nginx
- Migrate 2 tests from cnf-gotests
> cnf network: migrate system metallb tests

- tests/cnf/core/network/metallb/tests/layer2-test.go
Sorting isn't working when lastTimestamp is the same for multiple events. Hence, updating this to use firstTimestamp of the event.
> cnf network: fix metallb L2 flaky test

- tests/system-tests/rdscore/internal/rdscorecommon/sriov-validation.go
While re-running test container fails to start with next error message:
```
Error: 8021q: VLAN device already exists.
```
which is transient error and which is gone shortly after the failure.
As there's no hard requirement on how fast the pod should be recreated after scale down/up - extending timeout to 3 minutes
> system-test: increase time waiting for SR-IOV pod

- tests/cnf/core/network/metallb/tests/common.go
- tests/cnf/core/network/metallb/tests/metallb-nodeSelector.go
`TestID:53991` uses our `metallb:metallbtests` worker labels which is used across all metallb tests. As part of the test, we are removing the labels which leads to failure of subsequent nodeselector tests failure in a 3 worker node cluster. Instead, updated the test to use different custom label. 
`validatePrefix` checks for `len(bgpStatus.Routes)>0` even when `noRouteCheck is true`. In our tests we are using only single ip pool, so when route check is not required we should have this step. This is a flaky issue, probably passes when the bgp update to remove the route is not received before we are validating.
> cnf network: fix nodeselector test and validatePrefix

- tests/cnf/ran-deployment/README.md
- tests/cnf/ran-deployment/deploymenttypes/tests/deployment-types.go
- tests/cnf/ran-deployment/internal/ranconfig/config.go
Add environment variable setting (bool) to disable TLS certificate validation.
Needed for go-git library when git repo has a self-signed or internal certificate.
> Cert workaround

- tests/cnf/core/network/metallb/internal/cmd/cmd.go
- tests/cnf/core/network/metallb/internal/tsparams/mlbvars.go
- tests/cnf/core/network/metallb/tests/bfd-test.go
- tests/cnf/core/network/metallb/tests/bgp-remote-as-dynamic.go
- tests/cnf/core/network/metallb/tests/frrk8-tests.go
- tests/cnf/core/network/metallb/tests/metallb-crds.go
Modified the test logic to support clusters where IP forwarding is restricted by default.
> DRAFT: cnf-network: adapt tests for clusters with Restricted IP forwarding

- tests/cnf/core/network/policy/tests/multinetpolicysriov.go
- tests/cnf/core/network/sriov/tests/allmulti.go
- tests/cnf/core/network/sriov/tests/externalllymanaged.go
- tests/cnf/core/network/sriov/tests/metricsExporter.go
- tests/cnf/core/network/sriov/tests/mlxSecureBoot.go
- tests/cnf/core/network/sriov/tests/qinq.go
- tests/cnf/core/network/sriov/tests/rdmametricsapi.go
- tests/system-tests/vcore/internal/vcorecommon/sriov-validation.go
This change helps to reduce overall test runtime by avoiding node reboots when applying new policies to Mellanox (mlnx) devices. Previously, VF count mismatches could trigger unnecessary reboots, slowing down the CI cycle.
> cnf-network: change all sriov policy to use 5 VFs

- tests/system-tests/rdscore/tests/00_validate_top_level.go
(cherry picked from commit 3d0a8973bff3eac8bcd17a21ea44192554de23f0)
There's a known bug with EgressService so moving some tests out from the BeforeAll section
> system-test: re-shuffle EgressService tests. (#714)

- tests/system-tests/vcore/internal/vcorecommon/odf.go
Recent changes to the OCS types mean that the StorageCluster does not have the ManageNodes field anymore. In preparation for these changes in eco-goinfra, this PR removes the function's use in eco-gotests.
These tests are no longer relevant anyway so the plan to just remove the function has been okayed by system tests: [slack thread](https://redhat-internal.slack.com/archives/C06FJ6AC36Z/p1753449818278159).
> system-tests vcore: remove use of WithmanagedNodes

- tests/cnf/ran/gitopsztp/internal/tsparams/ztpvars.go
This PR adds a few more namespaces to the reporter for the gitopsztp suite. In particular, the klusterlet addon namespace is what contains the pods managing ConfigurationPolicies, which are good to have to investigate any failures of a policy to apply on the spoke. Some tests also modify sriov configuration on the spoke, so that namespace has been added too for completeness
> cnf ran: add more spoke logs to gitopsztp

- tests/hw-accel/README.md
- tests/hw-accel/internal/deploy/csv-utils.go
- tests/hw-accel/internal/deploy/operator-installer.go
- tests/hw-accel/internal/deploy/operator-uninstaller.go
- tests/hw-accel/nfd/features/tests/features-test.go
- tests/hw-accel/nfd/internal/nfddelete/custom_resources.go
- tests/hw-accel/nfd/internal/nfdhelpers/config.go
- tests/hw-accel/nfd/internal/set/featurelist.go
- tests/hw-accel/nfd/internal/set/nfd-cr-utils.go
- tests/hw-accel/nfd/internal/wait/wait.go
- tests/hw-accel/nfd/nfdparams/consts.go
add new oepratorinstaller, seperate cr utils, make nfd using it and update Readme. 
Added new struct (operator installer/uninstaller) and functions for handle operator installation using OLM.
separate CR deployment in this case nfd (cr-utils).
Update NFD Readme with all the necessary information.
> hwaccel: add new operator installer. separate CR utils for NFD.

- tests/lca/imagebasedupgrade/mgmt/upgrade/tests/e2e-upgrade-test.go
Based in the skip rules, seems like the z-stream scenario should be the first.
> lca ibu: Shuffle the z-stream scenario to be the first

- tests/cnf/core/network/metallb/tests/frrk8-tests.go
Issue running on new cluster with node naming convention worker0 rather then worker-0.
> cnf:network fix issue with hardcoded node name

- tests/cnf/core/network/day1day2/internal/tsparams/day1day2vars.go
- tests/cnf/core/network/metallb/internal/metallbenv/metallbenv.go
- tests/cnf/core/network/metallb/internal/tsparams/mlbvars.go
- tests/cnf/core/network/metallb/tests/layer2-test.go
- tests/cnf/core/network/policy/tests/multinetpolicysriov.go
- tests/cnf/core/network/sriov/internal/tsparams/sriovvars.go
- tests/cnf/core/network/sriov/tests/allmulti.go
- tests/cnf/core/network/sriov/tests/externalllymanaged.go
- tests/cnf/core/network/sriov/tests/metricsExporter.go
- tests/cnf/core/network/sriov/tests/mlxSecureBoot.go
- tests/cnf/core/network/sriov/tests/qinq.go
- tests/cnf/core/network/sriov/tests/rdmametricsapi.go
- tests/system-tests/vcore/internal/vcorecommon/sriov-validation.go
- Flaky issue where metallb speaker daemonset deletion check is skipped and old speaker daemonset is considered as new daemonset.
- Flaky issue where Events sorting needs to use both FirstTimestamp and LastTimestamp
- 6 VFs needed for test ID 67820. Updating VFs=6 all over the suite
- Dumping nmstate operator pods status when a test fails. This is to capture flaky issues of nmstate configuration.
> cnf network: fix multiple test issues

- .coderabbit.yaml
Noticed on #848 that unless you add the double asterisks, coderabbit will still include files under the directory.
Related-to: rh-ecosystem-edge/eco-goinfra#1156
> coderabbit: fix path filters
