rh-ecosystem-edge/eco-gotests

tests/lca/imagebasedupgrade/cnf/upgrade-talm/internal/tsparams/const.go
tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/prep-abort-test.go

adding ibu prep abort test case

ibu cnf: add prep abort test case

---

tests/lca/imagebasedupgrade/mgmt/negative/internal/tsparams/const.go
tests/lca/imagebasedupgrade/mgmt/negative/internal/tsparams/negativevars.go
tests/lca/imagebasedupgrade/mgmt/negative/negative_suite_test.go
tests/lca/imagebasedupgrade/mgmt/negative/tests/immutable-seedimage.go

Add negative test suite to contain MGMT IBU negative tests

mgmt ibu: add negative test suite

---

tests/lca/imagebasedupgrade/cnf/upgrade-talm/internal/tsparams/const.go
tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/upgrade-abort-test.go

adding upgrade abort test case

ready-for-final-review: ibu cnf: add upgrade abort test case

---

tests/system-tests/internal/reboot/reboot.go
tests/system-tests/ran-du/tests/hard-reboot.go
tests/system-tests/ran-du/tests/soft-reboot.go

- use IfNotPresent pull policy for ipmitool container
- use delete workload script for reboot tests cleanup

system-tests: update ran-du reboot tests

---

tests/system-tests/ran-du/tests/sriovfecnodeconfig-status.go

In some cases such as when running the test after a reboot it takes a few minutes until the SriovFecNodeConfig resource gets reconciled.

system-tests: wait for SriovFecNodeConfig resource to be configured

---

tests/cnf/core/network/dpdk/dpdk_suite_test.go
tests/cnf/core/network/dpdk/internal/dpdkenv/dpdkenv.go
tests/cnf/core/network/dpdk/tests/rootless.go
tests/cnf/core/network/internal/cmd/cmd.go
tests/cnf/core/network/internal/netenv/netenv.go
tests/cnf/core/network/internal/netparam/netvars.go
tests/cnf/core/network/sriov/tests/qinq.go

Add two test dpdk test cases
1. 802.1AD
2. 802.1Q

cnf network: add qinq dpdk tc

---

tests/cnf/ran/powermanagement/internal/helper/helper.go
tests/cnf/ran/powermanagement/internal/tsparams/consts.go
tests/cnf/ran/powermanagement/tests/cpufreq.go

Adding a test case for Reserved Core Frequency Tuning.

Added tests for reserved core frequency tuning

---

tests/lca/imagebasedupgrade/cnf/internal/validations/post_ibu_validations.go

kcat command may fail so retrying multiple times until the command exist without errors.

lca: cnf retry kcat command execution

---

tests/lca/imagebasedupgrade/mgmt/upgrade/tests/e2e-upgrade-test.go

Tests updating ibu stage from upgrade to prep.

lca: negative test to cover unsupported stage update.

---

tests/cnf/core/network/internal/netparam/netvars.go
tests/cnf/core/network/sriov/tests/qinq.go

Add Bond test and nmstate test cases

cnf network: add qinq nmstate test case

---

tests/lca/imagebasedupgrade/mgmt/internal/brutil/const.go

Fixes an error in the storage location for backup resources

ibu mgmt: fix backup storage location

---

tests/system-tests/ran-du/tests/workload-guaranteed-force-delete.go

Depends-On: https://github.com/openshift-kni/eco-goinfra/pull/488
Reference: https://issues.redhat.com/browse/OCPBUGS-34812

system-tests: ran-du: force delete guaranteed pod

---

images/cnf/network/eco-gotests-rootless-dpdk/Dockerfile

Adding tcpdump package and bumping up base image

cnf network: update Dockerfile for dpdk client image

---

tests/lca/imagebasedupgrade/cnf/internal/validations/post_ibu_validations.go

Sometimes retrieving the seed image info may fail so re-trying until no errors are reported.

lca: cnf: Retry seed image info retrieval in post validations

---

tests/cnf/ran/ztp/internal/helper/helper.go
tests/cnf/ran/ztp/internal/helper/policiesapp.go
tests/cnf/ran/ztp/internal/tsparams/consts.go
tests/cnf/ran/ztp/internal/tsparams/ztpvars.go
tests/cnf/ran/ztp/tests/ztp-argocd-policies-app.go
tests/cnf/ran/ztp/tests/ztp-machine-config.go

Adds the policies app and machine config tests. Also removes an unused variable from ztpvars.

cnf ran: ztp policies app and machine config migration

---

go.mod
go.sum
images/cnf/network/eco-gotests-network-client/Dockerfile
tests/cnf/core/network/sriov/tests/allmulti.go
vendor/github.com/openshift-kni/eco-goinfra/pkg/nad/masterplugin.go
vendor/github.com/openshift-kni/eco-goinfra/pkg/nad/nadtypes.go
vendor/github.com/openshift-kni/eco-goinfra/pkg/pod/network.go
vendor/github.com/openshift-kni/eco-goinfra/pkg/sriov/network.go
vendor/modules.txt

Adding sriov test cases for 4.16 feature allmulti

cnf network: backport-allmulti-sriov-4-14

---

tests/cnf/core/network/sriov/tests/qinq.go

https://github.com/openshift-kni/eco-gotests/pull/100 port to main branch

cnf network: QinQ TC update

---

tests/hw-accel/nfd/features/tests/features-test.go

Remove assertion on error messages and just log them

hwaccel: change log test

---

.golangci.yml
tests/accel/internal/accelconfig/config.go
tests/accel/internal/accelinittools/accelinittools.go
tests/accel/internal/accelparams/const.go

Adding accel team folder and internal packages

accel: add internal folder

---

tests/system-tests/vcore/internal/vcorecommon/helm.go
tests/system-tests/vcore/internal/vcorecommon/redis.go

fix helm redis deployment failure

vCore: fix helm redis deployment failure

---

tests/system-tests/vcore/internal/vcorecommon/odf.go
tests/system-tests/vcore/internal/vcorecommon/redis.go

odf nodes usage refactoring: matchExpressions changes

vcore: odf nodes usage refactoring

---

tests/system-tests/vcore/internal/config-files/redis-custom-values.yaml
tests/system-tests/vcore/internal/vcorecommon/loki-operator.go
tests/system-tests/vcore/internal/vcorecommon/redis.go
tests/system-tests/vcore/internal/vcoreparams/const.go

change ObjectBucketClaim storageClass to the ocs-storagecluster-ceph-rgw

vcore: change ObjectBucketClaim storageClass noobaa -> ceph-rgw

---

tests/system-tests/vcore/internal/vcorecommon/loki-operator.go

noobaa: increase configmap timeout

noobaa: increase configmap timeout

---

tests/system-tests/rdscore/README.md
tests/system-tests/rdscore/internal/rdscorecommon/hard-reboot.go
tests/system-tests/rdscore/internal/rdscorecommon/ipvlan-validation.go
tests/system-tests/rdscore/internal/rdscorecommon/macvlan-validation.go
tests/system-tests/rdscore/internal/rdscoreconfig/config.go
tests/system-tests/rdscore/internal/rdscoreconfig/default.yaml
tests/system-tests/rdscore/tests/00_validate_top_level.go

IPVLAN connectivity test added: different nodes & same node

RDS Core: IPVLAN connectivity test added

---

tests/system-tests/rdscore/internal/rdscorecommon/kernel-crash-kdump.go

Existing 1 minute polling is not always enough for the cluster to recover so extending it.

system-test: Extend polling interval for kdump tests

---

tests/cnf/core/network/internal/netparam/netvars.go
tests/cnf/core/network/sriov/tests/qinq.go

Updating Mlx Bluefield device ID

cnf network: qinq - mlx device id update

---

.github/workflows/eco-goinfra-bump.yml
.github/workflows/makefile.yml
Dockerfile

Related to:
- https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2360
- https://github.com/openshift-kni/eco-goinfra/pull/626

Update Go to v1.22.6

---

tests/assisted/ztp/operator/internal/tsparams/operatorvars.go
tests/assisted/ztp/operator/operator_suite_test.go
tests/assisted/ztp/spoke/internal/tsparams/spokevars.go
tests/assisted/ztp/spoke/spoke_suite_test.go

Add missing schemes to the reporter

assisted ztp: add schemes to reporter

---

images/cnf/network/eco-gotests-network-client/Dockerfile

Added net-tools package for arp binary

cnf network: update Dockerfile of network client

---

tests/cnf/core/network/internal/netnmstate/netnmstate.go

backport https://github.com/openshift-kni/eco-gotests/pull/211

[release-4.16]cnf-network: changed func isNMStateDeployedAndReady

---

tests/cnf/core/network/internal/netnmstate/netnmstate.go

backport https://github.com/openshift-kni/eco-gotests/pull/211

[release-4.15]cnf-network: changed func isNMStateDeployedAndReady

---

tests/cnf/core/network/internal/netnmstate/netnmstate.go

backport https://github.com/openshift-kni/eco-gotests/pull/211

[release-4.14]cnf-network: changed func isNMStateDeployedAndReady

---

tests/assisted/ztp/operator/internal/tsparams/operatorvars.go
tests/assisted/ztp/operator/tests/additional-trust-bundle.go
tests/assisted/ztp/operator/tests/build-artifacts-rootfs.go
tests/assisted/ztp/operator/tests/infraenv-multiarch-image.go
tests/assisted/ztp/operator/tests/osimage-clusterimageset-test.go

Updates references to WaitForDiscoveryISO to use Eventually container instead

assisted ztp: change wait for discovery iso to eventually

---

tests/cnf/core/network/sriov/tests/rdmametrics.go

- Added NAD verification before creating pod.

cnf network: fix rdma metrics tests

---

tests/cnf/core/network/metallb/internal/frr/frr.go
tests/cnf/core/network/metallb/tests/bfd-test.go
tests/cnf/core/network/metallb/tests/bgp-connect-time-tests.go
tests/cnf/core/network/metallb/tests/bgp-tests.go
tests/cnf/core/network/metallb/tests/common.go

cnf network: Add metallb bgp connect time tc

---

tests/system-tests/internal/mirroring/mirror-images.go
tests/system-tests/vcore/internal/vcorecommon/helper.go

vcore: modify mirror image cmd

---

tests/lca/imagebasedupgrade/cnf/upgrade-talm/internal/tsparams/const.go
tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/e2e-upgrade-test.go

Depends-On: https://github.com/openshift-kni/eco-goinfra/pull/708

lca cnf: use IBGU in e2e-upgrade-test

---

tests/cnf/core/network/metallb/tests/frrk8-tests.go

metallb label was not being removed
Removed afterall

cnf: network - fix frrk8 label

---

tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/rollback-after-failed-upgrade-test.go

make rollback-after-failed-upgrade-test more robust by:
- creating Abort IBGU in AfterEach function so that IBU resources turns into the Idle stage after the test runs
- adding initMonitorTimeout to the IBU spec so that the Rollback is started after 5 minutes
- waiting until the Prep stage is complete before checking for the node availability
- adding an extra check for the SSH port availability to avoid cases where the api becomes temporarily unavailable
- adding retries for retrieving the stateroot name after pivot
- moving the seedImageVersion outside BeforeEach as the IBU resource may not have the SeedImageRef.Version set at that point 
Depends-On: https://github.com/openshift-kni/eco-goinfra/pull/723

lca cnf: make rollback-after-failed-upgrade-test more robust

---

tests/lca/imagebasedupgrade/mgmt/upgrade/tests/e2e-upgrade-test.go

Automating the addition of required manifests and the post upgrade check that the proper module was loaded.

lca mgmt ibu Automating IBU of a cluster with KMM.

---

.github/workflows/eco-goinfra-bump.yml
Makefile

- Updates the eco-goinfra bump action to run daily and use the existing pull-request action

infra: use pr action for eco-goinfra bump

---

tests/cnf/core/network/sriov/tests/externalllymanaged.go

https://issues.redhat.com/browse/OCPBUGS-44284

cnf-network: SR-IOV removal test is commented

---

tests/assisted/ztp/internal/setup/setup.go
tests/assisted/ztp/operator/tests/https-webserver-setup-test.go
tests/assisted/ztp/operator/tests/osimage-clusterimageset-test.go

- Increase timeout for namespace deletion during test cleanup

assisted ztp: increase namespace deletion timeout

---

tests/internal/reporter/schemes.go
tests/lca/imagebasedinstall/mgmt/deploy/internal/tsparams/deployvars.go
tests/lca/imagebasedinstall/mgmt/deploy/tests/e2e-deploy-test.go
tests/lca/imagebasedinstall/mgmt/internal/mgmtconfig/config.go

- Add options for deploying with siteconfig to IBIO tests
- Add test case for IPv6 proxy + DHCP

ibi mgmt: add siteconfig option to ibio test

---

tests/cnf/core/network/day1day2/tests/day1day2.go

Removed the test due to the bug https://issues.redhat.com/browse/OCPBUGS-42031 which is not going to be fixed

cnf-network: remove 'Day2 Bond: change mode configuration test'

---

tests/assisted/ztp/operator/tests/infraenv-multiarch-image.go

- Fixes multiarch test failures in environments using image caching

assisted ztp: fix multiarch tests in cached environments

---

tests/cnf/core/network/sriov/internal/tsparams/consts.go
tests/cnf/core/network/sriov/tests/rdmametricsapi.go

`rdmametricsapi.go`
Test Cases for 4.18 RDMA CNI feature with SriovNetworkPoolConfig API
`rdmametrics.go`
Removed this file

cnf network: add rdma cni test cases

---

images/rhwa/dast/Dockerfile
images/rhwa/dast/config/rapidastConfig.yaml

Dockerfile that provides the capability of running rapidast test from eco-gotest code.

[rhwa] rapidast container definition

---

tests/assisted/ztp/internal/ztpconfig/config.go
tests/assisted/ztp/operator/tests/infraenv-multiarch-image.go

- Add override to retrieve pull-secret from file system rather than hub cluster

assisted ztp: add pull-secret override variable

---

tests/cnf/core/network/metallb/internal/frr/frr.go
tests/cnf/core/network/metallb/internal/tsparams/consts.go
tests/cnf/core/network/metallb/tests/bgp-remote-as-dynamic.go
tests/cnf/core/network/metallb/tests/common.go
tests/cnf/core/network/metallb/tests/frrk8-tests.go

Adding dynamic bgppeer remoteAS test cases

cnf network: add bgp dynamic remoteAS test cases

---

tests/system-tests/rdscore/internal/rdscorecommon/metallb-graceful-restart.go

Better handling of intermittent issues

system-test: Retry pod retrieval and reconnection on error

---

tests/cnf/core/network/internal/netconfig/config.go
tests/cnf/core/network/sriov/internal/sriovenv/bmc.go
tests/cnf/core/network/sriov/internal/sriovenv/sriovenv.go
tests/cnf/core/network/sriov/internal/tsparams/consts.go
tests/cnf/core/network/sriov/internal/tsparams/sriovvars.go
tests/cnf/core/network/sriov/tests/externalllymanaged.go
tests/cnf/core/network/sriov/tests/mlxSecureBoot.go
tests/cnf/core/network/sriov/tests/qinq.go

https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-77014&revision=14626915

cnf-network: add mlxSecureBoot test

---

tests/system-tests/rdscore/internal/rdscorecommon/egress-service.go
tests/system-tests/rdscore/tests/00_validate_top_level.go

Access backend pods via _LoadBalancer_ service with _ExternalTrafficPolicy=Cluster_

system-test: Validate pods via LoadBalancer service with ETP=Cluster

---

tests/cnf/core/network/metallb/internal/tsparams/mlbvars.go
tests/cnf/core/network/metallb/tests/bgp-remote-as-dynamic.go

Last two test cases of the epic. Two multi-hop test cases

cnf: networking - Add bgp dynamic multihop tc

---

images/cnf/network/eco-gotests-network-client/Dockerfile
tests/cnf/core/network/internal/netenv/netenv.go
tests/cnf/core/network/internal/netparam/netvars.go
tests/cnf/core/network/policy/tests/multinetpolicy_bondoversriov.go
tests/cnf/core/network/sriov/internal/sriovenv/sriovenv.go
tests/cnf/core/network/sriov/tests/exposemtu.go
tests/cnf/core/network/sriov/tests/externalllymanaged.go
tests/cnf/core/network/sriov/tests/metricsExporter.go
tests/cnf/core/network/sriov/tests/mlxSecureBoot.go
tests/cnf/core/network/sriov/tests/paralleldraining.go
tests/cnf/core/network/sriov/tests/rdmametricsapi.go

- New file `multinetpolicy_bondoversriov.go` covering Multi Network Policy tests for bond cni (over sr-iov)
- Updated eco-gotest client image Dockerfile with `nmap` package

cnf network: multi-netpolicy bond cni tests

---

tests/system-tests/internal/remote/cmd.go

* check if debug pod's already running and remove it if needed
* allow to customize image name
* adjusted _nodeSelector_

system-test: refactor ExecuteOnNodeWithPrivilegedDebugPod method

---

tests/assisted/ztp/internal/find/find.go
tests/assisted/ztp/internal/ztpconfig/config.go

- Prevents errors during configuration gathering from crashing test

assisted ztp: add error checking to ztpconfig constructor

---

tests/cnf/core/network/policy/tests/multinetpolicy_bondoversriov.go
tests/cnf/core/network/policy/tests/multinetpolicy_ipvlan.go

Changes to address CI run failures due to racy scenario:
- Added 2 steps to delete pods and NADs before deleting test namespace.
- Added 5sec wait between Multi-NetPolicy creation and test validation, [as the plugin takes a short time to implement the policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/#pod-lifecycle) and we have no other better way to verify that before test validation.

cnf network: fix mnp tests

---

tests/lca/imagebasedupgrade/mgmt/internal/mgmtconfig/config.go
tests/lca/imagebasedupgrade/mgmt/upgrade/tests/e2e-upgrade-test.go

Automating a test for different NTP source.

lca ibu: Check for different NTP source

---

tests/cnf/core/network/metallb/internal/frr/frr.go
tests/cnf/core/network/metallb/internal/tsparams/consts.go
tests/cnf/core/network/metallb/tests/bgp-gracefulrestart.go
tests/cnf/core/network/metallb/tests/bgp-tests.go

https://polarion.engineering.redhat.com/polarion/#/project/OSE/wiki/CNF/CNF%20MetalLB%20Graceful%20Restart

cnf-network: Added 2 GracefulRestart tests

---

tests/cnf/ran/talm/internal/mount/mount.go

Some commands executed by talm backup may not return the output occasionally, so this PR changes the behavior to retry until an output is found.

cnf ran: fix talm backup automation issue

---

tests/assisted/ztp/operator/operator_suite_test.go

- Fixes order in which we check that the environment is healthy

assisted ztp: fix operator beforesuite ordering

---

tests/lca/imagebasedupgrade/mgmt/upgrade/tests/e2e-upgrade-test.go

The test will silently pass in case z-stream
IBU was performed.

lca ibu: check on z-stream upgrade

---

tests/system-tests/rdscore/internal/rdscorecommon/mount_namespace.go

Added extra validation and retries to the commands that are executed on the remote nodes to prevent issues with malformed output that makes tests panic:
```code
I0106 11:51:59.489310   35463 pod.go:503] Execute command [chroot /rootfs /bin/sh -c readlink /proc/$(pgrep kubelet)/ns/mnt] in the pod machine-config-daemon-qtkvl container machine-config-daemon in namespace openshift-machine-config-operator
[PANICKED] Test Panicked
In [It] at: /usr/local/go/src/runtime/panic.go:115 @ 01/06/25 11:51:59.661
runtime error: index out of range [1] with length 1
Full Stack Trace
github.com/openshift-kni/eco-gotests/tests/system-tests/rdscore/internal/rdscorecommon.mountNamespaceEncapsulation({0xc00060bc70, 0x47})
/home/testuser/tests/system-tests/rdscore/internal/rdscorecommon/mount_namespace.go:70 …
```

system-test: retry commands on the nodes

---

tests/system-tests/internal/remote/cmd.go

- more debug logs added
- ss.Output replaced with the ss.CombinedOutput since it returns more debug info in case of the failure

System Test, RDS Core:ExecCmdOnHost method enhancements

---

tests/cnf/core/network/internal/netenv/netenv.go
tests/cnf/core/network/internal/netenv/sriov.go
tests/cnf/core/network/metallb/internal/tsparams/consts.go
tests/cnf/core/network/metallb/metallb_suite_test.go
tests/cnf/core/network/metallb/tests/bgp-gracefulrestart.go
tests/cnf/core/network/metallb/tests/bgp-tests.go
tests/cnf/core/network/metallb/tests/common.go

https://polarion.engineering.redhat.com/polarion/#/project/OSE/wiki/CNF/CNF%20MetalLB%20Graceful%20Restart

cnf-network: Added bfd graceful restart tests

---

tests/cnf/core/network/metallb/tests/common.go
tests/cnf/core/network/metallb/tests/metallb-crds.go

https://gitlab.cee.redhat.com/cnf/cnf-gotests/-/blob/master/test/network/metallb/tests/metallb-crds.go?ref_type=heads

cnf-network: MetealLB new CRD test migration

---

tests/system-tests/internal/supporttools/tcpdump.go
tests/system-tests/internal/supporttools/traceroute.go
tests/system-tests/rdscore/internal/rdscorecommon/metallb-traffic-segregation.go
tests/system-tests/rdscore/tests/00_validate_top_level.go

deploying tcpdump pod per worker node

System Test, RDS Core - increase tcpdump pods count

---

tests/system-tests/rdscore/tests/00_validate_top_level.go

Feature is not longer relevant so removing tests

system-test: removed GracefulRestart tests

---

tests/system-tests/rdscore/internal/rdscorecommon/egress-ip.go

test verification changed from the one specific node to the rest not rebooted

system-test: eIP fail-over test enhancements

---

tests/lca/imagebasedinstall/mgmt/deploy/tests/common.go
tests/lca/imagebasedinstall/mgmt/deploy/tests/reinstall-test.go
tests/lca/imagebasedinstall/mgmt/internal/mgmtconfig/config.go

- Update structure used for setting up reinstall test
- Add cluster ID check to reinstall test

ibi mgmt: enhance setup and test of ibbf

---

tests/assisted/ztp/operator/tests/https-webserver-setup-test.go

- Updates https-webserver test to use PV for storing OS image

assisted ztp: add fix for https-webserver test

---

tests/system-tests/rdscore/internal/rdscorecommon/sriov-validation.go

(cherry picked from commit 196f59ff93bb45196cf68d0166b4f16418bb3ab5)

system-test: wait for pod to be Ready before sending traffic

---

.github/workflows/eco-goinfra-bump.yml
.github/workflows/makefile.yml
.golangci.yml
Dockerfile
README.md
go.mod
scripts/golangci-lint.sh
tests/cnf/core/network/sriov/tests/metricsExporter.go

Related to: 
- https://github.com/openshift-kni/eco-goinfra/pull/937
- https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2855

Update Go to v1.24.1

---

tests/lca/imagebasedinstall/mgmt/deploy/tests/common.go
tests/lca/imagebasedinstall/mgmt/deploy/tests/reinstall-test.go
tests/lca/imagebasedinstall/mgmt/internal/mgmtconfig/config.go

- Move full re-install steps to IBIO IBBF test
- Remove dataimage workaround from siteconfig IBBF test

ibi mgmt: remove workaround for dataimage

---

tests/system-tests/rdscore/internal/rdscorecommon/frr-bgp.go
tests/system-tests/rdscore/internal/rdscorecommon/metallb-graceful-restart.go
tests/system-tests/rdscore/internal/rdscorecommon/metallb-traffic-segregation.go
tests/system-tests/rdscore/internal/rdscoreconfig/config.go
tests/system-tests/rdscore/internal/rdscoreconfig/default.yaml

make metallb ffr pods namespace configurable

System Test: RDS Core - make metallb ffr pods namespace configurable

---

tests/hw-accel/kmm/internal/kmmparams/const.go
tests/hw-accel/kmm/internal/kmmparams/kmmvars.go
tests/hw-accel/kmm/modules/internal/tsparams/kmm-vars.go
tests/hw-accel/kmm/modules/modules_suite_test.go
tests/hw-accel/kmm/modules/tests/taint-tolerations-test.go

- Added tests for KMM tolerations
- Updated some vars and consts

hw-accel: add taint/tolerations tests for KMM

---

tests/system-tests/internal/supporttools/traceroute.go
tests/system-tests/rdscore/internal/rdscorecommon/metallb-traffic-segregation.go

- change traceroute deployment name
- filter-out frr pods running on the master nodes

System Test: traceroute method adjustments

---

tests/cnf/core/network/internal/netconfig/config.go
tests/cnf/core/network/internal/netenv/netenv.go
tests/cnf/core/network/sriov/internal/sriovenv/bmc.go
tests/cnf/core/network/sriov/internal/sriovenv/sriovenv.go
tests/cnf/core/network/sriov/internal/tsparams/consts.go
tests/cnf/core/network/sriov/internal/tsparams/sriovvars.go
tests/cnf/core/network/sriov/tests/mlxSecureBoot.go

https://github.com/openshift-kni/eco-gotests/pull/306

[release-4.17] cnf-network: add mlxSecureBoot test

---

tests/cnf/core/network/sriov/tests/qinq.go

Backport 
https://github.com/openshift-kni/eco-gotests/pull/238
https://github.com/openshift-kni/eco-gotests/pull/242

cnf network: Fix QinQ regex validation

---

tests/system-tests/rdscore/internal/rdscorecommon/sriov-validation.go

(cherry picked from commit 496d45d73571565933bf6daec408b7bf4ea5868d)

system-test: fix logging issue for failed deployments (#529)

---

tests/system-tests/internal/supporttools/tcpdump.go

Fix inaccuracy in the _ScanTCPDumpPodLogs_
Current flow is:
- retrieve log
- if it's empty retry
- if it's not empty - search for the matching string
Proposed change is:
- retrieve log
- if it's empty - retry
- if it's not empty - search for the matching string
- if match found - success
- if no match found - retrieve newer log and search in the newer content

system-tests: retry logs retrieval until match found

---

tests/system-tests/internal/supporttools/tcpdump.go

(cherry picked from commit 2a0a36ed6ecd40d08b06d04708ed572eb9d05ddc)

system-tests: retry logs retrieval until match found (#540)

---

tests/system-tests/rdscore/tests/00_validate_top_level.go

(cherry picked from commit 344bf646d03f2ca3535d68520ea578ec7794a10c) 
(cherry picked from commit d458cb88dfe70021e0d8f906d76026d6181e961d)

system-test: update function name for SR-IOV tests (#542) (#543)

---

tests/cnf/core/network/policy/tests/multinetpolicy_bondoversriov.go
tests/cnf/core/network/policy/tests/multinetpolicy_ipvlan.go

Now that the [bug](https://issues.redhat.com/browse/OCPBUGS-44354) is fixed for this test case, identified another validation issue in automation

cnf network: fix validation for multi-netpolicy

---

tests/cnf/core/network/policy/tests/multinetpolicy_bondoversriov.go
tests/cnf/core/network/policy/tests/multinetpolicy_ipvlan.go

backport https://github.com/openshift-kni/eco-gotests/pull/548

cnf network: fix validation for multi-netpolicy [4.18]

---

tests/lca/imagebasedinstall/mgmt/deploy/tests/reinstall-test.go

- Add IPv6 + proxy reinstall test
- Move siteconfig reinstall steps into shared function

ibi mgmt: add ibbf test for IPv6 proxy scenario

---

tests/cnf/core/network/sriov/tests/qinq.go

backport https://github.com/openshift-kni/eco-gotests/pull/557

cnf network: add Mlx BF check [4.18]

---

tests/cnf/core/network/metallb/internal/tsparams/consts.go
tests/cnf/core/network/metallb/tests/bfd-test.go
tests/cnf/core/network/metallb/tests/bgp-multiservice.go
tests/cnf/core/network/metallb/tests/bgp-tests.go
tests/cnf/core/network/metallb/tests/common.go
tests/cnf/core/network/metallb/tests/frrk8-tests.go
tests/cnf/core/network/metallb/tests/layer2-test.go
tests/cnf/core/network/metallb/tests/metallb-crds.go
tests/cnf/core/network/metallb/tests/metallb-nodeSelector.go

test migration:
https://gitlab.cee.redhat.com/cnf/cnf-gotests/-/blob/master/test/network/metallb/tests/bgp-multiservice.go?ref_type=heads

cnf-network: Added Metallb BGP Multi-Service Validation

---

tests/hw-accel/kmm/modules/tests/webhook-test.go

Add tests for KMM tolerations checks on webhook server

hw-accel: add webhook tests for kmm tolerations

---

tests/cnf/ran/talm/tests/talm-precache.go

Test case `48902 Tests image precaching - operators` fails to cleanup the CGU it creates, causing issues with other test cases. This PR addresses it by deleting the CGU directly. The rest of the resources will be suffixed and should already be deleted.

cnf ran: fix cleanup issue in talm precache

---

tests/cnf/core/network/sriov/tests/webhook-matchConditions.go

Added Eventually for webhook validations to avoid racy situation

cnf network: fix sriov webhook test

---

tests/cnf/core/network/internal/netenv/netenv.go
tests/cnf/core/network/metallb/tests/bfd-test.go
tests/cnf/core/network/metallb/tests/metallb-crds.go

Updated variable names and error messages for better clarity in BFD tests. Adjusted worker node selection logic, introduced proper resource cleanup in AfterAll and AfterEach blocks, and modified timeout durations to improve test reliability. Changes ensure improved readability, maintainability, and robustness of the test suite.

cnf-network: Refactor BFD test logic and enhance error handling

---

tests/system-tests/rdscore/internal/rdscorecommon/sriov-pod-level-bond.go

This makes troubleshooting easier as it shows pods' names and their phase(_Pending, Running, Failed, etc_)

system-test: Log bogus pods for pod-level bonding tests

---

tests/system-tests/vcore/internal/vcorecommon/loki-operator.go

will be replaced with the ClusterLogForwarder object on the later stage. Code is not in use anyway

System Test: vcore test suite, remove clusterLogging object usage

---

tests/system-tests/rdscore/tests/00_validate_top_level.go

Stress testing for SR-IOV operator during pod level bonding testing

system-test: stress test for SR-IOV bond tests

---

tests/hw-accel/internal/deploy/deploy-nfd.go
tests/hw-accel/nfd/features/internal/helpers/test-helper-functions.go
tests/hw-accel/nfd/features/tests/features-test.go
tests/hw-accel/nfd/internal/wait/wait.go

Changing  some of the pod waiting and pulling for nfd

hwaccel: change nfd pods waiting and pulling

---

.golangci.yml
scripts/golangci-lint.sh
tests/cnf/ran/talm/internal/mount/mount.go

* Auto migrated the config to v2
* Updated install script
* Switched off a couple staticcheck checks that generated many errors on existing code
* Did minor refactor of a function to satisfy the one remaining staticcheck issue

lint: update to golangci-lint v2

---

tests/cnf/core/network/metallb/internal/frr/frr.go
tests/cnf/core/network/metallb/internal/metallbenv/metallbenv.go
tests/cnf/core/network/metallb/internal/tsparams/mlbvars.go
tests/cnf/core/network/metallb/tests/bgp-tests.go

Migrate tests from https://gitlab.cee.redhat.com/cnf/cnf-gotests/-/blob/master/test/network/metallb/tests/bgp-test.go?ref_type=heads

cnf network: bgptests migrate from cnf-gotest

---

tests/cnf/core/network/metallb/tests/common.go
tests/cnf/core/network/metallb/tests/metallb-nodeSelector.go

Adding two more metallb nodeselector test cases from cnf gotest

cnf network: add metallb nodeselector test cases

---

tests/cnf/core/network/internal/define/nad.go
tests/cnf/core/network/metallb/internal/frr/frr.go
tests/cnf/core/network/metallb/internal/tsparams/consts.go
tests/cnf/core/network/metallb/tests/bgp-remote-as-dynamic.go
tests/cnf/core/network/metallb/tests/bgp-unnumbered.go
tests/cnf/core/network/metallb/tests/common.go

Epic: BGP Unnumbered test cases

cnf network: add bgp unnumbered test cases

---

tests/cnf/core/network/internal/netparam/netvars.go
tests/cnf/core/network/sriov/tests/qinq.go

Add deviceID for the mellanox ConnectX6 interface

add-mlx-connect6-deviceid

---

tests/cnf/core/network/metallb/internal/tsparams/consts.go
tests/cnf/core/network/metallb/internal/tsparams/mlbvars.go
tests/cnf/core/network/metallb/tests/common.go
tests/cnf/core/network/metallb/tests/pool-selector.go

Migrate pool-selector tests to eco-gotests

cnf network: pool-selector tests

---

tests/cnf/core/network/metallb/tests/bfd-test.go
tests/cnf/core/network/metallb/tests/metallb-crds.go

Reverts openshift-kni/eco-gotests#615

Revert "cnf network: Remove unnecessary GW mode reversion calls"

---

tests/hw-accel/internal/deploy/deploy-nfd.go
tests/hw-accel/nfd/features/tests/features-test.go

make sure that the right image is used in custom catalog case

hwaccel: fixing wrong CR image issue during tests 

---

tests/hw-accel/kmm/mcm/tests/multi-stage.go

- removing test that is not required any longer

hw-accel: remove KMM-HUB test

---

tests/system-tests/rdscore/internal/rdscorecommon/log-forwarding.go

- increased log messages count
- skip broken unmarshal failure
- added log message demag print-out

System Test: cluster log forwarding test adjustments

---

tests/system-tests/internal/reboot/reboot.go
tests/system-tests/ran-du/tests/hard-reboot.go

- hard reboot worker nodes covering both sno and mno workers
- update reboot wait logic

system-tests: ran-du refactor hard reboot tests for mno setup

---

tests/lca/imagebasedinstall/mgmt/deploy/tests/reinstall-test.go

- Adds test case IDs to our IBBF test cases

ibi mgmt: add test case ids for ibbf tests

---

tests/cnf/core/network/sriov/internal/sriovenv/sriovenv.go
tests/cnf/core/network/sriov/internal/tsparams/consts.go
tests/cnf/core/network/sriov/tests/metricsExporter.go
tests/cnf/core/network/sriov/tests/webhook-matchConditions.go

backport sriov webhook injector test cases

backport-sriov-webhook-injector-test-case

---

tests/system-tests/internal/ptp/ptp.go

- Add retry mechanism to isClockSync() with 6 attempts and 10s delays
- Standardize retry intervals across PTP validation functions
- Enhance error reporting with retry count information
Increases reliability of PTP validation.

system-tests: ran-du: Improve PTP clock sync validation with retry logic

---

tests/system-tests/rdscore/tests/00_validate_top_level.go

(cherry picked from commit 3d0a8973bff3eac8bcd17a21ea44192554de23f0) 
(cherry picked from commit 5686efc632b6421cb365e943feb71171276d0011)

system-test: re-shuffle EgressService tests. (#714) (#715)

---

tests/lca/imagebasedinstall/mgmt/deploy/tests/reinstall-test.go

This reverts commit 023ee4f32107cac0dec698f7606f40e7beb3ace7.

Revert "ibi mgmt: add dataimage finalizer workaround for ibbf"

---

tests/system-tests/internal/link/link.go

(cherry picked from commit 245de1d88736009ea1b338a88801a0a977e6f92c)

system-tests: make "link" structure exported (#789)

---

tests/system-tests/rdscore/internal/rdscorecommon/whereabouts-deployment.go
tests/system-tests/rdscore/tests/00_validate_top_level.go

(cherry picked from commit 57b4a6c773cb26c53c8ea1f2ebd3ba6706ff0824)

system-tests: Whereabouts tests for node drain scenario (#802)

---

tests/system-tests/rdscore/internal/rdscorecommon/sriov-pod-level-bond.go

(cherry picked from commit 64319003956ee01d699ddb139b6aa34c6b9e3e03)

system-tests: updated getPodObjectByNamePattern
